import type { Metadata } from "next";
import { jersey } from "./ui/fonts";
import "./globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(jersey.variable, "antialiased")}>
        <main>{children}</main>
      </body>
    </html>
  );
}
